CREATE TABLE [dbo].[tbl_Customers] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [CustomerTypeId]     INT            NOT NULL,
    [ReturnIntervalId]   INT            NOT NULL,
    [PrimaryContactName] VARCHAR (100)  NOT NULL,
    [TenantId]           NVARCHAR (128) NOT NULL,
    [FirmName]           VARCHAR (100)  NULL,
    [ReffName]           VARCHAR (100)  NULL,
    [AddressLine1]       NVARCHAR (MAX) NOT NULL,
    [AddressLine2]       NVARCHAR (MAX) NULL,
    [City]               VARCHAR (50)   NOT NULL,
    [StateId]            INT            NOT NULL,
    [CountryId]          INT            NOT NULL,
    [DateOfBirth]        DATETIME       NULL,
    [MobileNumber]       VARCHAR (12)   NULL,
    [EmailAddress]       VARCHAR (30)   NULL,
    [AdharNumber]        VARCHAR (12)   NOT NULL,
    [PanNumber]          VARCHAR (10)   NOT NULL,
    [ITFileNumber]       VARCHAR (10)   NULL,
    [ITUserId]           VARCHAR (50)   NULL,
    [ITPassword]         VARCHAR (30)   NULL,
    [GSTNumber]          VARCHAR (12)   NULL,
    [GSTFileNumber]      VARCHAR (10)   NULL,
    [GSTUserId]          VARCHAR (50)   NULL,
    [GSTPassword]        VARCHAR (30)   NULL,
    [EwayBillId]         VARCHAR (50)   NULL,
    [EwayPassword]       VARCHAR (30)   NULL,
    [VATId]              VARCHAR (50)   NULL,
    [VATPassword]        VARCHAR (30)   NULL,
    [AccountantId]       INT            NULL,
    [AdvocateId]         INT            NULL,
    [CreatedOn]          DATETIME       CONSTRAINT [DF_tbl_Customers_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          INT            NULL,
    [ModifiedOn]         DATETIME       NULL,
    [ModifiedBy]         INT            NULL,
    [RowVersion]         ROWVERSION     NOT NULL,
    [IsActive]           BIT            NOT NULL,
    [IsDeleted]          BIT            NOT NULL,
    CONSTRAINT [PK_tbl_Customers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_tbl_Customers_tbl_AccountantAdvocate] FOREIGN KEY ([AccountantId]) REFERENCES [dbo].[tbl_AccountantAdvocate] ([Id]),
    CONSTRAINT [FK_tbl_Customers_tbl_AccountantAdvocate1] FOREIGN KEY ([AdvocateId]) REFERENCES [dbo].[tbl_AccountantAdvocate] ([Id]),
    CONSTRAINT [FK_tbl_Customers_tbl_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[tbl_Country] ([Id]),
    CONSTRAINT [FK_tbl_Customers_tbl_Customers] FOREIGN KEY ([TenantId]) REFERENCES [dbo].[tbl_Tenant] ([TenantId]),
    CONSTRAINT [FK_tbl_Customers_tbl_Lookup] FOREIGN KEY ([CustomerTypeId]) REFERENCES [dbo].[tbl_Lookup] ([Id]),
    CONSTRAINT [FK_tbl_Customers_tbl_Lookup1] FOREIGN KEY ([ReturnIntervalId]) REFERENCES [dbo].[tbl_Lookup] ([Id]),
    CONSTRAINT [FK_tbl_Customers_tbl_State] FOREIGN KEY ([StateId]) REFERENCES [dbo].[tbl_State] ([Id])
);

